# Reduce memory usage at the cost of performance
smol = true
telemetry = false

[debug]
editor = "code"

[install]
optional = true
peer = true

[console]
depth = 3

[test]
root = "./tests"
smol = true
coverage = true
coverageThreshold = { lines = 0.80, functions = 0.80 }
coverageReporter = ["text", "lcov"]
coverageDir = "./coverage"